### ISSUE TITLE
"DNS name was empty" error

### ISSUE THREAD

**Issue by ghost** [cw-ansible/cw.letsencrypt#1]
On stage 1 I get this error:

```
TASK [cw.letsencrypt : Run letsencrypt stage 1] ********************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the 
environment value uses the full variable syntax ('{{letsencrypt_certificates}}').
This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False
 in ansible.cfg.
failed: [localhost] (item={u'domains': [{u'name': u'snipped.com', u'cn': True}, u'snipped.com']}) => {"failed": true, "item": {"domains": [{"cn": true, "name": "snipped.com"}, "snipped.com"]}, "msg": "u'Error creating new authz :: DNS name was empty'"}
```

My host has a working local dns name but it is not using public DNS over the internet, is that causing a problem? My default main.yml contains:

```

---

# Set of default values that can be overriden in each
# letsencrypt_certificates definition. See the letsencrypt module
# documentation for details on the meaning of these keys.
letsencrypt_defaults:
  dir: store/letsencrypt-test
  email: 'it@snip.com'
  host: hostname.snip.com 
  webroot: /opt/gitlab/embedded/service/gitlab-rails/public
  min_days: 7
  domains_key_size: 4096
  user_key_size: 4096  
  staging: yes


# A list of dictionnary suitable for the letsencrypt module.
# Each item can be either a FQDN or a dict. See the letsencrypt module (the
# domains option) for description of the keys.
letsencrypt_certificates:
  - domains:
      - name: snip.com
        cn: yes        
      - hostname.snip.com

```
